Transform: 'AWS::Serverless-2016-10-31'
Parameters:
    SamMultipler:
        Description: "SAM multiplier. Make this really big to have a party :)"
        Type: "String"
    OriginUrl:
        Description: "The origin url to allow CORS requests from. This will be the base URL of your static SAM website."
        Type: "String"
Resources:
    GetSAMPartyCount:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs10.x
            CodeUri: ./
            Environment:
                Variables:
                    SAM_MULTIPLIER: !Ref SamMultipler
                    ORIGIN_URL: !Ref OriginUrl
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /sam
                  Method: get
            ### NEW !!!      
            AutoPublishAlias: live
            DeploymentPreference:
                Type: Linear10PercentEvery10Minutes
                Alarms:
                # A list of alarms that you want to monitor
                    - !Ref AliasErrorMetricGreaterThanZeroAlarm
                    - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm    
                Hooks:
                # Validation lambda functions that are run before & after
                    PreTraffic: !Ref PreTrafficLambdaFunction        
                #    PostTraffic: !Ref PostTrafficLambdaFunction

    AliasErrorMetricGreaterThanZeroAlarm:
        Type: "AWS::CloudWatch::Alarm"
        Properties:
            AlarmDescription: Lambda Function Error > 0
            ComparisonOperator: GreaterThanThreshold
            Dimensions:
                - Name: Resource
                  Value: !Sub "${GetSAMPartyCount}:live"
                - Name: FunctionName
                  Value: !Ref GetSAMPartyCount
            EvaluationPeriods: 2
            MetricName: Errors
            Namespace: AWS/Lambda
            Period: 60
            Statistic: Sum
            Threshold: 0            

    LatestVersionErrorMetricGreaterThanZeroAlarm:
        Type: "AWS::CloudWatch::Alarm"
        Properties:
            AlarmDescription: Lambda Function Error > 0
            ComparisonOperator: GreaterThanThreshold
            Dimensions:
                - Name: Resource
                  Value: !Sub "${GetSAMPartyCount}:live"
                - Name: FunctionName
                  Value: !Ref GetSAMPartyCount
                - Name: ExecutedVersion
                  Value: !GetAtt GetSAMPartyCount.Version.Version
            EvaluationPeriods: 2
            MetricName: Errors
            Namespace: AWS/Lambda
            Period: 60
            Statistic: Sum
            Threshold: 0    

    PreTrafficLambdaFunction:
        Type: AWS::Serverless::Function 
        Properties:
            Handler: preTrafficHook.handler
            Policies:
               - Version: "2012-10-17"
                 Statement:
                 - Effect: "Allow"
                    Action:
                      - "codedeploy:PutLifecycleEventHookExecutionStatus"
                    Resource:
                      !Sub 'arn:${AWS::Partition}:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
               - Version: "2012-10-17            
                 Statement:
                 - Effect: "Allow"
                    Action:
                      - "lambda:InvokeFunction"
                    Resource:  !Ref GetSAMPartyCount.Version
        Runtime: nodejs10.x            
        FunctionName: 'CodeDeployHook_preTrafficHook'
        DeploymentPreference:
            Enabled: false
            Role: ""
        Environment:
            Variables:
               CurrentVersion: !Ref GetSAMPartyCount.Version     
                      